## 3.9 - Need to Create a final scraping file that does the following
     - imports product links
     - initializles scraper
     - initalizes scraping to csv function
     - runs scraping function for first 5k, second 5k, 3rd 5k,and last 1.somethingk

### Import All Product Links

In [1]:
import pickle

In [2]:
infile = open('product_links.pkl','rb')
product_links = pickle.load(infile)
infile.close()

In [9]:
len(product_links[5000:10000])

5000

In [10]:
len(product_links[0:5000])

5000

### Initalizing Scraping Functions

In [3]:
from selectorlib import Extractor
import requests 
import csv
import numpy as np
from numpy import random
import time,os

In [4]:
e = Extractor.from_yaml_file('Wine_Bottle_Template.yml')

In [5]:
def scrape(url):    
    headers = {
        'authority': 'www.wine.com',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36',
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'accept-language': 'en-US,en;q=0.9',
    }
    r = requests.get(url, headers=headers)
    return e.extract(r.text, base_url=url)

In [28]:
def batch(start,end,filename):
    data = []
    counter = 0
    csv_columns = ['Name', 'Varietal', 'Region', 'Price', 'Dosage', 'Online_Rating', 'Total_Ratings', 'sommelier_ratings']
    csv_file = filename
    for product in product_links[start:end]:
        data.append(scrape(product))
        counter += 1
        if counter == (end-start):
            with open(csv_file, 'w') as csvfile:
                writer = csv.DictWriter(csvfile, fieldnames= csv_columns)
                writer.writeheader()
                for bottles in data:
                    writer.writerow(bottles)

In [26]:
def batch_test(start,end,filename):
    data = []
    counter = 0
    csv_columns = ['Name', 'Varietal', 'Region', 'Price', 'Dosage', 'Online_Rating', 'Total_Ratings', 'sommelier_ratings']
    csv_file = filename
    for product in product_links[start:end]:
        data.append(scrape(product))
        counter += 1
        if counter == (end-start):
            with open(csv_file, 'w') as csvfile:
                writer = csv.DictWriter(csvfile, fieldnames= csv_columns)
                writer.writeheader()
                for bottles in data:
                    writer.writerow(bottles)

## Scraping Products Final

In [7]:
import pandas as pd

### Scraping first 5k

In [8]:
batch(0,5000,'products_1.csv')

In [9]:
products_1 = pd.read_csv('products_1.csv')
products_1.head()

,Name,Varietal,Region,Price,Dosage,Online_Rating,Total_Ratings,sommelier_ratings
0,Dom. Lucien Barrot et Fils Chateauneuf-du-Pape...,Rhone Red Blends,"Chateauneuf-du-Pape, Rhone, France",40 99,750 ML,3.7,11 Ratings,WE 94 JD 92
1,Gemstone Vineyard Alluvial Selection Cabernet ...,Cabernet Sauvignon,"Yountville, Napa Valley, California",165,750 ML,0.0,0 Ratings,JD 95
2,Heritance Napa Valley Cabernet Sauvignon 2016,Cabernet Sauvignon,"Napa Valley, California",44 99,750 ML,0.0,0 Ratings,NaN
3,Tatomer Rose of Pinot Noir 2020,Rosé,"Edna Valley, Central Coast, California",28 99,750 ML,0.0,0 Ratings,WW 92
4,Chateau d'Issan Blason d'Issan (Futures Pre-Sa...,Bordeaux Red Blends,"Margaux, Bordeaux, France",26 97,750 ML,0.0,0 Ratings,JS 94 D 92

### Scraping second 5k

In [29]:
batch(5000,10000,'products_2.csv')

In [30]:
products_2 = pd.read_csv('products_2.csv')
products_2.head()

,Name,Varietal,Region,Price,Dosage,Online_Rating,Total_Ratings,sommelier_ratings
0,Leeuwin Estate Art Series Shiraz 2018,Syrah/Shiraz,"Margaret River, Western Australia, Australia",34 99,750 ML,0.0,0 Ratings,JH 96 W & S 91 WE 90
1,J.J. Vincent Pouilly-Fuisse Marie Antoinette 2018,Chardonnay,"Pouilly-Fuisse, Maconnais, Burgundy, France",24 99,750 ML,4.0,24 Ratings,BH 91 WW 90
2,Carmelo Patti Malbec 2017,Malbec,"Mendoza, Argentina",35 99,750 ML,0.0,0 Ratings,NaN
3,Tormaresca Chardonnay 2020,Chardonnay,"Puglia, Italy",12 99,750 ML,0.0,0 Ratings,NaN
4,Russian River Valley Winegrowers Venerations b...,Pinot Noir,"Russian River, Sonoma County, California",69 99,750 ML,0.0,0 Ratings,NaN

### Scraping third 5k

In [31]:
batch(10000,15000,'products_3.csv')

In [32]:
products_3 = pd.read_csv('products_3.csv')
products_3.head()

,Name,Varietal,Region,Price,Dosage,Online_Rating,Total_Ratings,sommelier_ratings
0,Domaine Bruno Clavelier Nuits-St-Georges Aux C...,Pinot Noir,"Nuits-St-Georges, Cote de Nuits, Cote d'Or, Bu...",165 97,750 ML,0.0,0 Ratings,NaN
1,Domaine de la Bergerie Cremant de Loire Brut 2017,Vintage Sparkling Wine,"Loire, France",27 99,750 ML,0.0,0 Ratings,NaN
2,Maison L'Envoye Moulin-a-Vent 2019,Gamay,"Beaujolais, Burgundy, France",18 99,750 ML,0.0,0 Ratings,NaN
3,Mending Wall Tournahu Vineyard Cabernet Sauvig...,Cabernet Sauvignon,"St. Helena, Napa Valley, California",124 99,750 ML,0.0,0 Ratings,JD 96
4,Domaine Perrot-Minot Nuits-Saint-Georges La Ri...,Pinot Noir,"Nuits-St-Georges, Cote de Nuits, Cote d'Or, Bu...",299 97,750 ML,0.0,0 Ratings,BH 93

### Scraping Last 1352k

In [33]:
batch(15000,16352,'products_4.csv')

In [34]:
products_4 = pd.read_csv('products_4.csv')
products_4.head()

,Name,Varietal,Region,Price,Dosage,Online_Rating,Total_Ratings,sommelier_ratings
0,A. Margaine Extra Brut,Non-Vintage Sparkling Wine,"Champagne, France",66 99,750 ML,0.0,0 Ratings,RP 93 V 90
1,Chateau Pavie 2017,Bordeaux Red Blends,"St. Emilion, Bordeaux, France",449 99,750 ML,0.0,0 Ratings,JD 99 RP 99 JS 97 WS 97 D 96 WE 95
2,Giornata Luna Matta Vineyard Nebbiolo 2017,Nebbiolo,"Paso Robles, Central Coast, California",49 99,750 ML,0.0,0 Ratings,NaN
3,Mandala Wines Yarra Valley Pinot Noir 2020,Pinot Noir,"Yarra Valley, Victoria, Australia",30,750 ML,0.0,0 Ratings,WW 91
4,Chateau de Nalys Saintes Pierres de Nalys Chat...,Rhone Red Blends,"Chateauneuf-du-Pape, Rhone, France",57 99,750 ML,3.8,8 Ratings,JD 92 V 92 JS 91 RP 91 WS 90